require File.join(File.dirname(__FILE__), "allegro_graph", "server")
require File.join(File.dirname(__FILE__), "allegro_graph", "catalog")
require File.join(File.dirname(__FILE__), "allegro_graph", "repository")
require File.join(File.dirname(__FILE__), "allegro_graph", "session")
require File.join(File.dirname(__FILE__), "allegro_graph", "federation")
